// <copyright file="SwaggerPetstoreOpenApi30Client.cs" company="APIMatic">
// SwaggerPetstoreOpenApi30.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Authentication;
using APIMatic.Core.Utilities;
using APIMatic.Core.Utilities.Logger.Configuration;
using Microsoft.Extensions.Configuration;
using SwaggerPetstoreOpenApi30.Standard.Apis;
using SwaggerPetstoreOpenApi30.Standard.Authentication;
using SwaggerPetstoreOpenApi30.Standard.Http.Client;
using SwaggerPetstoreOpenApi30.Standard.Logging;
using System;
using System.Collections.Generic;

namespace SwaggerPetstoreOpenApi30.Standard
{
    /// <summary>
    /// The gateway for the SDK. This class acts as a factory for Api and holds the
    /// configuration of the SDK.
    /// </summary>
    public sealed class SwaggerPetstoreOpenApi30Client : IConfiguration
    {
        // A map of environments and their corresponding servers/baseurls
        private static readonly Dictionary<Environment, Dictionary<Enum, string>> EnvironmentsMap =
            new Dictionary<Environment, Dictionary<Enum, string>>
        {
            {
                Environment.Production, new Dictionary<Enum, string>
                {
                    { Server.Default, "https://petstore3.swagger.io/api/v3" },
                    { Server.AuthServer, "https://petstore3.swagger.io/oauth" },
                }
            },
        };

        private readonly GlobalConfiguration globalConfiguration;
        private SdkLoggingConfiguration sdkLoggingConfiguration;
        private const string userAgent = "DotNet-SDK/1.1.6 (OS: {os-info}, Engine: {engine}/{engine-version})";
        private readonly HttpCallback httpCallback;
        private readonly Lazy<PetApi> pet;
        private readonly Lazy<StoreApi> store;
        private readonly Lazy<UserApi> user;

        private SwaggerPetstoreOpenApi30Client(
            Environment environment,
            PetstoreAuthModel petstoreAuthModel,
            ApiKeyModel apiKeyModel,
            HttpCallback httpCallback,
            IHttpClientConfiguration httpClientConfiguration,
            SdkLoggingConfiguration sdkLoggingConfiguration)
        {
            this.Environment = environment;
            this.httpCallback = httpCallback;
            this.HttpClientConfiguration = httpClientConfiguration;
            this.sdkLoggingConfiguration = sdkLoggingConfiguration;
            PetstoreAuthModel = petstoreAuthModel;
            var petstoreAuthManager = new PetstoreAuthManager(petstoreAuthModel,
                () => globalConfiguration);
            ApiKeyModel = apiKeyModel;
            var apiKeyManager = new ApiKeyManager(apiKeyModel);
            globalConfiguration = new GlobalConfiguration.Builder()
                .AuthManagers(new Dictionary<string, AuthManager> {
                    {"petstore_auth", petstoreAuthManager},
                    {"api_key", apiKeyManager},
                })
                .ApiCallback(httpCallback)
                .HttpConfiguration(httpClientConfiguration)
                .ServerUrls(EnvironmentsMap[environment], Server.Default)
                .LoggingConfig(sdkLoggingConfiguration)
                .UserAgent(userAgent)
                .Build();
            PetstoreAuthCredentials = petstoreAuthManager;
            ApiKeyCredentials = apiKeyManager;

            this.pet = new Lazy<PetApi>(
                () => new PetApi(globalConfiguration));
            this.store = new Lazy<StoreApi>(
                () => new StoreApi(globalConfiguration));
            this.user = new Lazy<UserApi>(
                () => new UserApi(globalConfiguration));
        }

        /// <summary>
        /// Gets PetApi.
        /// </summary>
        public PetApi PetApi => this.pet.Value;

        /// <summary>
        /// Gets StoreApi.
        /// </summary>
        public StoreApi StoreApi => this.store.Value;

        /// <summary>
        /// Gets UserApi.
        /// </summary>
        public UserApi UserApi => this.user.Value;

        /// <summary>
        /// Gets the configuration of the Http Client associated with this client.
        /// </summary>
        public IHttpClientConfiguration HttpClientConfiguration { get; }

        /// <summary>
        /// Gets Environment.
        /// Current API environment.
        /// </summary>
        public Environment Environment { get; }

        /// <summary>
        /// Gets http callback.
        /// </summary>
        public HttpCallback HttpCallback => this.httpCallback;

        /// <summary>
        /// Gets the credentials to use with PetstoreAuth.
        /// </summary>
        public IPetstoreAuthCredentials PetstoreAuthCredentials { get; private set; }

        /// <summary>
        /// Gets the credentials model to use with PetstoreAuth.
        /// </summary>
        public PetstoreAuthModel PetstoreAuthModel { get; private set; }

        /// <summary>
        /// Gets the credentials to use with ApiKey.
        /// </summary>
        public IApiKeyCredentials ApiKeyCredentials { get; private set; }

        /// <summary>
        /// Gets the credentials model to use with ApiKey.
        /// </summary>
        public ApiKeyModel ApiKeyModel { get; private set; }

        /// <summary>
        /// Gets the URL for a particular alias in the current environment and appends
        /// it with template parameters.
        /// </summary>
        /// <param name="alias">Default value:DEFAULT.</param>
        /// <returns>Returns the baseurl.</returns>
        public string GetBaseUri(Server alias = Server.Default)
        {
            return globalConfiguration.ServerUrl(alias);
        }

        /// <summary>
        /// Creates an object of the SwaggerPetstoreOpenApi30Client using the values provided for the builder.
        /// </summary>
        /// <returns>Builder.</returns>
        public Builder ToBuilder()
        {
            Builder builder = new Builder()
                .Environment(this.Environment)
                .HttpCallback(httpCallback)
                .LoggingConfig(sdkLoggingConfiguration)
                .HttpClientConfig(config => config.Build());

            if (PetstoreAuthModel != null)
            {
                builder.PetstoreAuthCredentials(PetstoreAuthModel.ToBuilder().Build());
            }

            if (ApiKeyModel != null)
            {
                builder.ApiKeyCredentials(ApiKeyModel.ToBuilder().Build());
            }

            return builder;
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            return
                $"Environment = {this.Environment}, " +
                $"HttpClientConfiguration = {this.HttpClientConfiguration}, ";
        }

        /// <summary>
        /// Creates the client using builder.
        /// </summary>
        /// <returns> SwaggerPetstoreOpenApi30Client.</returns>
        internal static SwaggerPetstoreOpenApi30Client CreateFromEnvironment()
        {
            var builder = new Builder();

            string environment = System.Environment.GetEnvironmentVariable("SWAGGER_PETSTORE_OPEN_API_30_STANDARD_ENVIRONMENT");
            string oauthClientId = System.Environment.GetEnvironmentVariable("SWAGGER_PETSTORE_OPEN_API_30_STANDARD_OAUTH_CLIENT_ID");
            string oauthRedirectUri = System.Environment.GetEnvironmentVariable("SWAGGER_PETSTORE_OPEN_API_30_STANDARD_OAUTH_REDIRECT_URI");
            string apiKey = System.Environment.GetEnvironmentVariable("SWAGGER_PETSTORE_OPEN_API_30_STANDARD_API_KEY");

            if (environment != null)
            {
                builder.Environment(CoreHelper.JsonDeserialize<Environment>($"\"{environment}\""));
            }

            if (oauthClientId != null && oauthRedirectUri != null)
            {
                builder.PetstoreAuthCredentials(new PetstoreAuthModel
                .Builder(oauthClientId, oauthRedirectUri)
                .Build());
            }

            if (apiKey != null)
            {
                builder.ApiKeyCredentials(new ApiKeyModel
                .Builder(apiKey)
                .Build());
            }

            return builder.Build();
        }

        /// <summary>
        /// Creates the client from configuration.
        /// </summary>
        /// <returns> SwaggerPetstoreOpenApi30Client.</returns>
        public static SwaggerPetstoreOpenApi30Client FromConfiguration(IConfigurationSection configuration) =>
            Builder.FromConfiguration(configuration).Build();

        /// <summary>
        /// Builder class.
        /// </summary>
        public class Builder
        {
            private Environment _environment = SwaggerPetstoreOpenApi30.Standard.Environment.Production;
            private PetstoreAuthModel _petstoreAuthModel = new PetstoreAuthModel();
            private ApiKeyModel _apiKeyModel = new ApiKeyModel();
            private HttpClientConfiguration.Builder _httpClientConfig = new HttpClientConfiguration.Builder();
            private HttpCallback _httpCallback;
            private SdkLoggingConfiguration _sdkLoggingConfiguration;

            /// <summary>
            /// Sets credentials for PetstoreAuth.
            /// </summary>
            /// <param name="petstoreAuthModel">PetstoreAuthModel.</param>
            /// <returns>Builder.</returns>
            public Builder PetstoreAuthCredentials(PetstoreAuthModel petstoreAuthModel)
            {
                _petstoreAuthModel = petstoreAuthModel ??
                    throw new ArgumentNullException(nameof(petstoreAuthModel));
                return this;
            }

            /// <summary>
            /// Sets credentials for ApiKey.
            /// </summary>
            /// <param name="apiKeyModel">ApiKeyModel.</param>
            /// <returns>Builder.</returns>
            public Builder ApiKeyCredentials(ApiKeyModel apiKeyModel)
            {
                _apiKeyModel = apiKeyModel ??
                    throw new ArgumentNullException(nameof(apiKeyModel));
                return this;
            }

            /// <summary>
            /// Sets Environment.
            /// </summary>
            /// <param name="environment"> Environment. </param>
            /// <returns> Builder. </returns>
            public Builder Environment(Environment environment)
            {
                _environment = environment;
                return this;
            }

            /// <summary>
            /// Sets HttpClientConfig.
            /// </summary>
            /// <param name="action"> Action. </param>
            /// <returns>Builder.</returns>
            public Builder HttpClientConfig(Action<HttpClientConfiguration.Builder> action)
            {
                if (action is null)
                {
                    throw new ArgumentNullException(nameof(action));
                }

                action(_httpClientConfig);
                return this;
            }

            private Builder HttpClientConfig(HttpClientConfiguration.Builder httpClientConfigurationBuilder)
            {
                if (httpClientConfigurationBuilder != null)
                {
                    _httpClientConfig = httpClientConfigurationBuilder;
                }

                return this;
            }

            /// <summary>
            /// Sets the default logging configuration, using the Console logger.
            /// </summary>
            /// <returns>Builder.</returns>
            public Builder LoggingConfig()
            {
                _sdkLoggingConfiguration = SdkLoggingConfiguration.Console();
                return this;
            }

            /// <summary>
            /// Sets the logging configuration using the provided <paramref name="action"/>.
            /// </summary>
            /// <param name="action">The action to perform on the logging configuration builder.</param>
            /// <returns>Builder.</returns>
            /// <exception cref="ArgumentNullException">Thrown when <paramref name="action"/> is null.</exception>
            public Builder LoggingConfig(Action<LogBuilder> action)
            {
                if (action is null) throw new ArgumentNullException(nameof(action));
                var logBuilder =
                    LogBuilder.CreateFromConfig(_sdkLoggingConfiguration ?? SdkLoggingConfiguration.Console());
                action(logBuilder);
                _sdkLoggingConfiguration = logBuilder.Build();
                return this;
            }

            internal Builder LoggingConfig(SdkLoggingConfiguration configuration)
            {
                _sdkLoggingConfiguration = configuration;
                return this;
            }

            /// <summary>
            /// Sets the HttpCallback for the Builder.
            /// </summary>
            /// <param name="httpCallback"> http callback. </param>
            /// <returns>Builder.</returns>
            public Builder HttpCallback(HttpCallback httpCallback)
            {
                _httpCallback = httpCallback;
                return this;
            }

            /// <summary>
            /// Creates an object of the SwaggerPetstoreOpenApi30Client using the values provided for the builder.
            /// </summary>
            /// <returns>SwaggerPetstoreOpenApi30Client.</returns>
            public SwaggerPetstoreOpenApi30Client Build()
            {
                if (_petstoreAuthModel.OauthClientId == null || _petstoreAuthModel.OauthRedirectUri == null)
                {
                    _petstoreAuthModel = null;
                }
                if (_apiKeyModel.ApiKey == null)
                {
                    _apiKeyModel = null;
                }
                return new SwaggerPetstoreOpenApi30Client(
                    _environment,
                    _petstoreAuthModel,
                    _apiKeyModel,
                    _httpCallback,
                    _httpClientConfig.Build(),
                    _sdkLoggingConfiguration);
            }

            /// <summary>
            /// Creates the client builder from configuration.
            /// </summary>
            /// <returns> Builder.</returns>
            public static Builder FromConfiguration(IConfigurationSection config)
            {
                var builder = new Builder();
                var options = config.Get<SwaggerPetstoreOpenApi30ClientOptions>();
                if (options == null) return builder;
                if (options.Environment != null)
                    builder.Environment(options.Environment.Value);
                if (options.PetstoreAuthCredentials != null)
                    builder.PetstoreAuthCredentials(PetstoreAuthModel.FromOptions(options.PetstoreAuthCredentials));
                if (options.ApiKeyCredentials != null)
                    builder.ApiKeyCredentials(ApiKeyModel.FromOptions(options.ApiKeyCredentials));
                if (options.HttpClientConfig != null)
                    builder.HttpClientConfig(Http.Client.HttpClientConfiguration.FromOptions(options.HttpClientConfig));
                if (options.LoggingConfig != null)
                    builder.LoggingConfig(LogBuilder.FromOptions(options.LoggingConfig));
                return builder;
            }
        }

        public class SwaggerPetstoreOpenApi30ClientOptions
        {
            public Environment? Environment { get; set; }
            public PetstoreAuthModelOptions PetstoreAuthCredentials { get; set; }
            public ApiKeyModelOptions ApiKeyCredentials { get; set; }
            public HttpClientConfigurationOptions HttpClientConfig { get; set; }
            public LoggingConfigOptions LoggingConfig { get; set; }
        }
    }
}
