// <copyright file="OauthProviderError.cs" company="APIMatic">
// SwaggerPetstoreOpenApi30.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;
using System.Xml.Serialization;

namespace SwaggerPetstoreOpenApi30.Standard.Models
{
    /// <summary>
    /// OauthProviderError.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    [XmlRoot("OAuthProviderError")]
    public enum OauthProviderError
    {
        /// <summary>
        ///The request is missing a required parameter, includes an unsupported parameter value (other than grant type), repeats a parameter, includes multiple credentials, utilizes more than one mechanism for authenticating the client, or is otherwise malformed.
        /// InvalidRequest.
        /// </summary>
        [XmlEnum("invalid_request")]
        [EnumMember(Value = "invalid_request")]
        InvalidRequest,

        /// <summary>
        ///Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method).
        /// InvalidClient.
        /// </summary>
        [XmlEnum("invalid_client")]
        [EnumMember(Value = "invalid_client")]
        InvalidClient,

        /// <summary>
        ///The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.
        /// InvalidGrant.
        /// </summary>
        [XmlEnum("invalid_grant")]
        [EnumMember(Value = "invalid_grant")]
        InvalidGrant,

        /// <summary>
        ///The authenticated client is not authorized to use this authorization grant type.
        /// UnauthorizedClient.
        /// </summary>
        [XmlEnum("unauthorized_client")]
        [EnumMember(Value = "unauthorized_client")]
        UnauthorizedClient,

        /// <summary>
        ///The authorization grant type is not supported by the authorization server.
        /// UnsupportedGrantType.
        /// </summary>
        [XmlEnum("unsupported_grant_type")]
        [EnumMember(Value = "unsupported_grant_type")]
        UnsupportedGrantType,

        /// <summary>
        ///The requested scope is invalid, unknown, malformed, or exceeds the scope granted by the resource owner.
        /// InvalidScope.
        /// </summary>
        [XmlEnum("invalid_scope")]
        [EnumMember(Value = "invalid_scope")]
        InvalidScope
    }
}