// <copyright file="OauthScopePetstoreAuth.cs" company="APIMatic">
// SwaggerPetstoreOpenApi30.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Xml.Serialization;

namespace SwaggerPetstoreOpenApi30.Standard.Models
{
    /// <summary>
    /// OauthScopePetstoreAuth.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    [XmlRoot("OAuth ScopePetstoreAuth")]
    public enum OauthScopePetstoreAuth
    {
        /// <summary>
        ///modify pets in your account
        /// Writepets.
        /// </summary>
        [XmlEnum("write:pets")]
        [EnumMember(Value = "write:pets")]
        Writepets,

        /// <summary>
        ///read your pets
        /// Readpets.
        /// </summary>
        [XmlEnum("read:pets")]
        [EnumMember(Value = "read:pets")]
        Readpets
    }

    internal static class OauthScopePetstoreAuthExtensions
    {
        internal static string GetValues(this IEnumerable<OauthScopePetstoreAuth> values) => values != null
            ? string.Join(" ", values.Select(s => s.GetValue()).Where(s => !string.IsNullOrEmpty(s)).ToArray())
            : null;

        private static string GetValue(this Enum value) =>
            value.GetType()
                .GetTypeInfo()
                .DeclaredMembers
                .SingleOrDefault(x => x.Name == value.ToString())
                ?.GetCustomAttribute<EnumMemberAttribute>(false)
                ?.Value;
    }
}