// <copyright file="Order.cs" company="APIMatic">
// SwaggerPetstoreOpenApi30.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Date.Xml;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using SwaggerPetstoreOpenApi30.Standard.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Xml;
using System.Xml.Linq;
using System.Xml.Schema;
using System.Xml.Serialization;

namespace SwaggerPetstoreOpenApi30.Standard.Models
{
    /// <summary>
    /// Order.
    /// </summary>
    [XmlRootAttribute("order")]
    public class Order : IXmlSerializable
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Order"/> class.
        /// </summary>
        public Order()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Order"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="petId">petId.</param>
        /// <param name="quantity">quantity.</param>
        /// <param name="shipDate">shipDate.</param>
        /// <param name="status">status.</param>
        /// <param name="complete">complete.</param>
        public Order(
            long? id = null,
            long? petId = null,
            int? quantity = null,
            DateTime? shipDate = null,
            Models.OrderStatus? status = null,
            bool? complete = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Id = id;
            this.PetId = petId;
            this.Quantity = quantity;
            this.ShipDate = shipDate;
            this.Status = status;
            this.Complete = complete;
        }

        /// <summary>
        /// Gets or sets Id.
        /// </summary>
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        [XmlElement("id")]
        public long? Id { get; set; }

        /// <summary>
        /// Gets or sets PetId.
        /// </summary>
        [JsonProperty("petId", NullValueHandling = NullValueHandling.Ignore)]
        [XmlElement("petId")]
        public long? PetId { get; set; }

        /// <summary>
        /// Gets or sets Quantity.
        /// </summary>
        [JsonProperty("quantity", NullValueHandling = NullValueHandling.Ignore)]
        [XmlElement("quantity")]
        public int? Quantity { get; set; }

        /// <summary>
        /// Gets or sets ShipDate.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("shipDate", NullValueHandling = NullValueHandling.Ignore)]
        [XmlElement("shipDate")]
        public DateTime? ShipDate { get; set; }

        /// <summary>
        /// Order Status
        /// </summary>
        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        [XmlElement("status")]
        public Models.OrderStatus? Status { get; set; }

        /// <summary>
        /// Gets or sets Complete.
        /// </summary>
        [JsonProperty("complete", NullValueHandling = NullValueHandling.Ignore)]
        [XmlElement("complete")]
        public bool? Complete { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Order : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {(this.Id == null ? "null" : this.Id.ToString())}");
            toStringOutput.Add($"PetId = {(this.PetId == null ? "null" : this.PetId.ToString())}");
            toStringOutput.Add($"Quantity = {(this.Quantity == null ? "null" : this.Quantity.ToString())}");
            toStringOutput.Add($"ShipDate = {(this.ShipDate == null ? "null" : this.ShipDate.ToString())}");
            toStringOutput.Add($"Status = {(this.Status == null ? "null" : this.Status.ToString())}");
            toStringOutput.Add($"Complete = {(this.Complete == null ? "null" : this.Complete.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Newtonsoft.Json.Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }

        /// <summary>
        /// Creates a new class instance from the given XDocument.
        /// </summary>
        /// <param name="xDoc">The xDocument.</param>
        /// <returns>A new class instance.</returns>
        public static Order FromXml(XDocument xDoc)
        {
            var id = (long?)xDoc.Root.Element("id");
            var petId = (long?)xDoc.Root.Element("petId");
            var quantity = (int?)xDoc.Root.Element("quantity");
            var shipDate = Rfc3339DateTimeXmlConverter.StringToRfc3339Date(xDoc.Root.Element("shipDate").Value).GetValueOrDefault();
            Models.OrderStatus status = default(Models.OrderStatus);

            if (xDoc.Root.Element("status") != null)
            {
                status = (Models.OrderStatus)Enum.Parse(typeof(Models.OrderStatus), xDoc.Root.Element("status").Value.TrimEnd().TrimStart());
            }

            var complete = (bool?)xDoc.Root.Element("complete");
            return new Order()
                {
                    Id=id,
                    PetId=petId,
                    Quantity=quantity,
                    ShipDate=shipDate,
                    Status=status,
                    Complete=complete,
                };
        }

        /// <summary>
        /// Returns xml schema.
        /// </summary>
        /// <returns>Xml schema object.</returns>
        public XmlSchema GetSchema()
        {
            return null;
        }

        /// <summary>
        /// Writes data to the XmlWriter.
        /// </summary>
        /// <param name="writer">XmlWriter object.</param>
        public void WriteXml(XmlWriter writer)
        {
            if (this.Id != null)
            {
                writer.WriteElementString("id", this.Id.ToString());
            }

            if (this.PetId != null)
            {
                writer.WriteElementString("petId", this.PetId.ToString());
            }

            if (this.Quantity != null)
            {
                writer.WriteElementString("quantity", this.Quantity.ToString());
            }

            if (this.ShipDate != null)
            {
                writer.WriteElementString("shipDate", Rfc3339DateTimeXmlConverter.Rfc3339DateToString(this.ShipDate));
            }

            if (this.Status != null)
            {
                writer.WriteElementString("status", this.Status.ToString());
            }

            if (this.Complete != null)
            {
                writer.WriteElementString("complete", this.Complete.ToString());
            }
        }

        /// <summary>
        /// Loads values from the given XmlReader object.
        /// </summary>
        /// <param name="reader">XmlReader object.</param>
        public void ReadXml(XmlReader reader)
        {
            var xmlStr = reader.ReadOuterXml();
            XDocument xDoc = XDocument.Parse(xmlStr);
            var obj = FromXml(xDoc);

            this.Id = obj.Id;
            this.PetId = obj.PetId;
            this.Quantity = obj.Quantity;
            this.ShipDate = obj.ShipDate;
            this.Status = obj.Status;
            this.Complete = obj.Complete;
        }
    }
}