// <copyright file="PetStatus.cs" company="APIMatic">
// SwaggerPetstoreOpenApi30.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;
using System.Xml.Serialization;

namespace SwaggerPetstoreOpenApi30.Standard.Models
{
    /// <summary>
    /// PetStatus.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    [XmlRoot("PetStatus")]
    public enum PetStatus
    {
        /// <summary>
        /// Available.
        /// </summary>
        [XmlEnum("available")]
        [EnumMember(Value = "available")]
        Available,

        /// <summary>
        /// Pending.
        /// </summary>
        [XmlEnum("pending")]
        [EnumMember(Value = "pending")]
        Pending,

        /// <summary>
        /// Sold.
        /// </summary>
        [XmlEnum("sold")]
        [EnumMember(Value = "sold")]
        Sold
    }
}