// <copyright file="IPetstoreAuthCredentials.cs" company="APIMatic">
// SwaggerPetstoreOpenApi30.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System.Collections.Generic;
using System.Threading.Tasks;

namespace SwaggerPetstoreOpenApi30.Standard.Authentication
{
    public interface IPetstoreAuthCredentials
    {
        /// <summary>
        /// Gets string value for oauthClientId.
        /// </summary>
        string OauthClientId { get; }

        /// <summary>
        /// Gets string value for oauthRedirectUri.
        /// </summary>
        string OauthRedirectUri { get; }

        /// <summary>
        /// Gets Models.OauthToken value for oauthToken.
        /// </summary>
        Models.OauthToken OauthToken { get; }

        /// <summary>
        /// Gets List of Models.OauthScopePetstoreAuth value for oauthScopes.
        /// </summary>
        List<Models.OauthScopePetstoreAuth> OauthScopes { get; }

        /// <summary>
        ///  Returns true if credentials matched.
        /// </summary>
        /// <param name="oauthClientId"> The string value for credentials.</param>
        /// <param name="oauthRedirectUri"> The string value for credentials.</param>
        /// <param name="oauthToken"> The Models.OauthToken value for credentials.</param>
        /// <param name="oauthScopes"> The List of Models.OauthScopePetstoreAuth value for credentials.</param>
        /// <returns>True if credentials matched.</returns>
        bool Equals(string oauthClientId, string oauthRedirectUri, Models.OauthToken oauthToken, List<Models.OauthScopePetstoreAuth> oauthScopes);

        /// <summary>
        /// Checks if token is expired.
        /// </summary>
        /// <returns> Returns true if token is expired.</returns>
        bool IsTokenExpired();

        /// <summary>
        /// Build an authorization URL for taking the user's consent to access data.
        /// </summary>
        /// <param name="state">An opaque state string.</param>
        /// <param name="additionalParameters">Additional parameters to add the the authorization URL.</param>
        /// <returns>Authorization URL.</returns>
        Task<string> BuildAuthorizationUrl(string state = null, Dictionary<string, object> additionalParameters = null);
    }
}