// <copyright file="PetstoreAuthManager.cs" company="APIMatic">
// SwaggerPetstoreOpenApi30.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using SwaggerPetstoreOpenApi30.Standard.Models;
using APIMatic.Core.Authentication;
using APIMatic.Core;
using System.Net.Http;
using SwaggerPetstoreOpenApi30.Standard.Exceptions;

namespace SwaggerPetstoreOpenApi30.Standard.Authentication
{
    /// <summary>
    /// PetstoreAuthManager Class.
    /// </summary>
    public class PetstoreAuthManager : AuthManager, IPetstoreAuthCredentials
    {
        private readonly Func<GlobalConfiguration> getGlobalConfiguration;

        /// <summary>
        /// Initializes a new instance of the <see cref="PetstoreAuthManager"/> class.
        /// </summary>
        /// <param name="petstoreAuth"> OAuth 2 Implicit Auth Model.</param>
        /// <param name="getGlobalConfiguration">A function that provides an instance of <see cref="GlobalConfiguration"/>.</param>
        internal PetstoreAuthManager(PetstoreAuthModel petstoreAuth,
            Func<GlobalConfiguration> getGlobalConfiguration)
        {
            this.OauthClientId = petstoreAuth?.OauthClientId;
            this.OauthRedirectUri = petstoreAuth?.OauthRedirectUri;
            this.OauthToken = petstoreAuth?.OauthToken;
            this.OauthScopes = petstoreAuth?.OauthScopes;
            this.getGlobalConfiguration = getGlobalConfiguration;
            Parameters(authParameter => authParameter
                .Header(headerParameter => headerParameter
                    .Setup("Authorization",
                        OauthToken?.AccessToken == null ? null : $"Bearer {OauthToken?.AccessToken}"
                    ).Required()));
        }

        /// <summary>
        /// Gets string value for oauthClientId.
        /// </summary>
        public string OauthClientId { get; }

        /// <summary>
        /// Gets string value for oauthRedirectUri.
        /// </summary>
        public string OauthRedirectUri { get; }

        /// <summary>
        /// Gets Models.OauthToken value for oauthToken.
        /// </summary>
        public Models.OauthToken OauthToken { get; }

        /// <summary>
        /// Gets List of Models.OauthScopePetstoreAuth value for oauthScopes.
        /// </summary>
        public List<Models.OauthScopePetstoreAuth> OauthScopes { get; }

        /// <summary>
        /// Check if credentials match.
        /// </summary>
        /// <param name="oauthClientId"> The string value for credentials.</param>
        /// <param name="oauthRedirectUri"> The string value for credentials.</param>
        /// <param name="oauthToken"> The Models.OauthToken value for credentials.</param>
        /// <param name="oauthScopes"> The List of Models.OauthScopePetstoreAuth value for credentials.</param>
        /// <returns> True if credentials matched.</returns>
        public bool Equals(string oauthClientId, string oauthRedirectUri, Models.OauthToken oauthToken, List<Models.OauthScopePetstoreAuth> oauthScopes)
        {
            return oauthClientId.Equals(this.OauthClientId)
                    && oauthRedirectUri.Equals(this.OauthRedirectUri)
                    && ((oauthToken == null && this.OauthToken == null) || (oauthToken != null && this.OauthToken != null && oauthToken.Equals(this.OauthToken)))
                    && ((oauthScopes == null && this.OauthScopes == null) || (oauthScopes != null && this.OauthScopes != null && oauthScopes.Equals(this.OauthScopes)));
        }

        /// <summary>
        /// Checks if token is expired.
        /// </summary>
        /// <returns> Returns true if token is expired.</returns>
        public bool IsTokenExpired()
        {
           if (this.OauthToken == null)
           {
               throw new InvalidOperationException("OAuth token is missing.");
           }
        
           return this.OauthToken.Expiry != null
               && this.OauthToken.Expiry < (long)DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1)).TotalSeconds;
        }

        /// <summary>
        /// Builds the authorization url for making authorized calls.
        /// </summary>
        /// <param name="state">State</param>        
        /// <param name="additionalParameters">Additional parameters to be appended</param>        
        public async Task<string> BuildAuthorizationUrl(string state = null, Dictionary<string, object> additionalParameters = null)
        {
            var request = await getGlobalConfiguration().GlobalRequestBuilder(Server.Default)
              .Setup(HttpMethod.Get, "/authorize")
              .Parameters(parameter => parameter
                .Query(queryParameter => queryParameter.Setup("response_type", "code"))
                .Query(queryParameter => queryParameter.Setup("client_id", OauthClientId))
                .Query(queryParameter => queryParameter.Setup("redirect_uri", OauthRedirectUri))
                .Query(queryParameter => queryParameter.Setup("scope", OauthScopes.GetValues()))
                .Query(queryParameter => queryParameter.Setup("state", state))
                .AdditionalQueries(additionalQuery => additionalQuery.Setup(additionalParameters)))
              .Build().ConfigureAwait(false);;
            return request.QueryUrl;
        }

        /// <summary>
        /// Validates the authentication parameters for the HTTP Request.
        /// </summary>
        public override void Validate()
        {
            base.Validate();
            if (OauthToken == null)
            {
                throw new ApiException(
                        "Client is not authorized.An OAuth token is needed to make API calls.");
            }

            if (IsTokenExpired())
            {
                throw new ApiException(
                        "OAuth token is expired. A valid token is needed to make API calls.");
            }
        }

    }

    public sealed class PetstoreAuthModel
    {
        internal PetstoreAuthModel()
        {
        }

        internal string OauthClientId { get; set; }

        internal string OauthRedirectUri { get; set; }

        internal Models.OauthToken OauthToken { get; set; }

        internal List<Models.OauthScopePetstoreAuth> OauthScopes { get; set; }

        /// <summary>
        /// Creates an object of the PetstoreAuthModel using the values provided for the builder.
        /// </summary>
        /// <returns>Builder.</returns>
        public Builder ToBuilder()
        {
            return new Builder(OauthClientId, OauthRedirectUri)
                .OauthToken(OauthToken)
                .OauthScopes(OauthScopes);
        }

        /// <summary>
        /// Builder class for PetstoreAuthModel.
        /// </summary>
        public class Builder
        {
            private string oauthClientId;
            private string oauthRedirectUri;
            private Models.OauthToken oauthToken;
            private List<Models.OauthScopePetstoreAuth> oauthScopes;

            public Builder(string oauthClientId, string oauthRedirectUri)
            {
                this.oauthClientId = oauthClientId ?? throw new ArgumentNullException(nameof(oauthClientId));
                this.oauthRedirectUri = oauthRedirectUri ?? throw new ArgumentNullException(nameof(oauthRedirectUri));
            }

            /// <summary>
            /// Sets OauthClientId.
            /// </summary>
            /// <param name="oauthClientId">OauthClientId.</param>
            /// <returns>Builder.</returns>
            public Builder OauthClientId(string oauthClientId)
            {
                this.oauthClientId = oauthClientId ?? throw new ArgumentNullException(nameof(oauthClientId));
                return this;
            }

            /// <summary>
            /// Sets OauthRedirectUri.
            /// </summary>
            /// <param name="oauthRedirectUri">OauthRedirectUri.</param>
            /// <returns>Builder.</returns>
            public Builder OauthRedirectUri(string oauthRedirectUri)
            {
                this.oauthRedirectUri = oauthRedirectUri ?? throw new ArgumentNullException(nameof(oauthRedirectUri));
                return this;
            }

            /// <summary>
            /// Sets OauthToken.
            /// </summary>
            /// <param name="oauthToken">OauthToken.</param>
            /// <returns>Builder.</returns>
            public Builder OauthToken(Models.OauthToken oauthToken)
            {
                this.oauthToken = oauthToken;
                return this;
            }

            /// <summary>
            /// Sets OauthScopes.
            /// </summary>
            /// <param name="oauthScopes">OauthScopes.</param>
            /// <returns>Builder.</returns>
            public Builder OauthScopes(List<Models.OauthScopePetstoreAuth> oauthScopes)
            {
                this.oauthScopes = oauthScopes;
                return this;
            }

            /// <summary>
            /// Creates an object of the PetstoreAuthModel using the values provided for the builder.
            /// </summary>
            /// <returns>PetstoreAuthModel.</returns>
            public PetstoreAuthModel Build()
            {
                return new PetstoreAuthModel()
                {
                    OauthClientId = this.oauthClientId,
                    OauthRedirectUri = this.oauthRedirectUri,
                    OauthToken = this.oauthToken,
                    OauthScopes = this.oauthScopes
                };
            }
        }

        internal static PetstoreAuthModel FromOptions(PetstoreAuthModelOptions options)
        {
            var builder = new Builder(options.OauthClientId, options.OauthRedirectUri);
            if (options.OauthToken != null)
                builder.OauthToken(options.OauthToken);
            if (options.OauthScopes != null)
                builder.OauthScopes(options.OauthScopes);
            return builder.Build();
        }
    }

    public class PetstoreAuthModelOptions
    {
        public string OauthClientId { get; set; }
        public string OauthRedirectUri { get; set; }
        public Models.OauthToken OauthToken { get; set; }
        public List<Models.OauthScopePetstoreAuth> OauthScopes { get; set; }
    }
}