// <copyright file="PetApi.cs" company="APIMatic">
// SwaggerPetstoreOpenApi30.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Types;
using APIMatic.Core.Utilities;
using SwaggerPetstoreOpenApi30.Standard.Exceptions;
using SwaggerPetstoreOpenApi30.Standard.Http.Client;
using SwaggerPetstoreOpenApi30.Standard.Http.Response;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace SwaggerPetstoreOpenApi30.Standard.Apis
{
    /// <summary>
    /// PetApi.
    /// </summary>
    public class PetApi : BaseApi
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PetApi"/> class.
        /// </summary>
        internal PetApi(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// Update an existing pet by Id.
        /// </summary>
        /// <param name="name">Required parameter: .</param>
        /// <param name="photoUrls">Required parameter: .</param>
        /// <param name="id">Optional parameter: .</param>
        /// <param name="category">Optional parameter: .</param>
        /// <param name="tags">Optional parameter: .</param>
        /// <param name="status">Optional parameter: pet status in the store.</param>
        /// <returns>Returns the ApiResponse of Models.Pet response from the API call.</returns>
        public ApiResponse<Models.Pet> UpdatePet(
                string name,
                List<string> photoUrls,
                long? id = null,
                Models.Category category = null,
                List<Models.Tag> tags = null,
                Models.PetStatus? status = null)
            => CoreHelper.RunTask(UpdatePetAsync(name, photoUrls, id, category, tags, status));

        /// <summary>
        /// Update an existing pet by Id.
        /// </summary>
        /// <param name="name">Required parameter: .</param>
        /// <param name="photoUrls">Required parameter: .</param>
        /// <param name="id">Optional parameter: .</param>
        /// <param name="category">Optional parameter: .</param>
        /// <param name="tags">Optional parameter: .</param>
        /// <param name="status">Optional parameter: pet status in the store.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.Pet response from the API call.</returns>
        public async Task<ApiResponse<Models.Pet>> UpdatePetAsync(
                string name,
                List<string> photoUrls,
                long? id = null,
                Models.Category category = null,
                List<Models.Tag> tags = null,
                Models.PetStatus? status = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.Pet>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Put, "/pet")
                  .WithAuth("petstore_auth")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))
                      .Form(form => form.Setup("name", name).Required())
                      .Form(form => form.Setup("photoUrls", photoUrls).Required())
                      .Form(form => form.Setup("id", id))
                      .Form(form => form.Setup("category", category))
                      .Form(form => form.Setup("tags", tags))
                      .Form(form => form.Setup("status", (status.HasValue) ? CoreHelper.JsonSerialize(status.Value).Trim('\"') : null))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Invalid ID supplied", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("Pet not found", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("422", CreateErrorCase("Validation exception", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("0", CreateErrorCase("Unexpected error", (errorReason, context) => new ApiException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Add a new pet to the store.
        /// </summary>
        /// <param name="name">Required parameter: .</param>
        /// <param name="photoUrls">Required parameter: .</param>
        /// <param name="id">Optional parameter: .</param>
        /// <param name="category">Optional parameter: .</param>
        /// <param name="tags">Optional parameter: .</param>
        /// <param name="status">Optional parameter: pet status in the store.</param>
        /// <returns>Returns the ApiResponse of Models.Pet response from the API call.</returns>
        public ApiResponse<Models.Pet> AddPet(
                string name,
                List<string> photoUrls,
                long? id = null,
                Models.Category category = null,
                List<Models.Tag> tags = null,
                Models.PetStatus? status = null)
            => CoreHelper.RunTask(AddPetAsync(name, photoUrls, id, category, tags, status));

        /// <summary>
        /// Add a new pet to the store.
        /// </summary>
        /// <param name="name">Required parameter: .</param>
        /// <param name="photoUrls">Required parameter: .</param>
        /// <param name="id">Optional parameter: .</param>
        /// <param name="category">Optional parameter: .</param>
        /// <param name="tags">Optional parameter: .</param>
        /// <param name="status">Optional parameter: pet status in the store.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.Pet response from the API call.</returns>
        public async Task<ApiResponse<Models.Pet>> AddPetAsync(
                string name,
                List<string> photoUrls,
                long? id = null,
                Models.Category category = null,
                List<Models.Tag> tags = null,
                Models.PetStatus? status = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.Pet>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/pet")
                  .WithAuth("petstore_auth")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))
                      .Form(form => form.Setup("name", name).Required())
                      .Form(form => form.Setup("photoUrls", photoUrls).Required())
                      .Form(form => form.Setup("id", id))
                      .Form(form => form.Setup("category", category))
                      .Form(form => form.Setup("tags", tags))
                      .Form(form => form.Setup("status", (status.HasValue) ? CoreHelper.JsonSerialize(status.Value).Trim('\"') : null))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Invalid input", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("422", CreateErrorCase("Validation exception", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("0", CreateErrorCase("Unexpected error", (errorReason, context) => new ApiException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Multiple status values can be provided with comma separated strings.
        /// </summary>
        /// <param name="status">Optional parameter: Status values that need to be considered for filter.</param>
        /// <returns>Returns the ApiResponse of List of Models.Pet response from the API call.</returns>
        public ApiResponse<List<Models.Pet>> FindPetsByStatus(
                Models.PetStatus? status = null)
            => CoreHelper.RunTask(FindPetsByStatusAsync(status));

        /// <summary>
        /// Multiple status values can be provided with comma separated strings.
        /// </summary>
        /// <param name="status">Optional parameter: Status values that need to be considered for filter.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of List of Models.Pet response from the API call.</returns>
        public async Task<ApiResponse<List<Models.Pet>>> FindPetsByStatusAsync(
                Models.PetStatus? status = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<List<Models.Pet>>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/pet/findByStatus")
                  .WithAuth("petstore_auth")
                  .Parameters(parameters => parameters
                      .Query(query => query.Setup("status", (status.HasValue) ? CoreHelper.JsonSerialize(status.Value).Trim('\"') : null))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Invalid status value", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("0", CreateErrorCase("Unexpected error", (errorReason, context) => new ApiException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
        /// </summary>
        /// <param name="tags">Optional parameter: Tags to filter by.</param>
        /// <returns>Returns the ApiResponse of List of Models.Pet response from the API call.</returns>
        public ApiResponse<List<Models.Pet>> FindPetsByTags(
                List<string> tags = null)
            => CoreHelper.RunTask(FindPetsByTagsAsync(tags));

        /// <summary>
        /// Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
        /// </summary>
        /// <param name="tags">Optional parameter: Tags to filter by.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of List of Models.Pet response from the API call.</returns>
        public async Task<ApiResponse<List<Models.Pet>>> FindPetsByTagsAsync(
                List<string> tags = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<List<Models.Pet>>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/pet/findByTags")
                  .WithAuth("petstore_auth")
                  .Parameters(parameters => parameters
                      .Query(query => query.Setup("tags", tags))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Invalid tag value", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("0", CreateErrorCase("Unexpected error", (errorReason, context) => new ApiException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Returns a single pet.
        /// </summary>
        /// <param name="petId">Required parameter: ID of pet to return.</param>
        /// <returns>Returns the ApiResponse of Models.Pet response from the API call.</returns>
        public ApiResponse<Models.Pet> GetPetById(
                long petId)
            => CoreHelper.RunTask(GetPetByIdAsync(petId));

        /// <summary>
        /// Returns a single pet.
        /// </summary>
        /// <param name="petId">Required parameter: ID of pet to return.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.Pet response from the API call.</returns>
        public async Task<ApiResponse<Models.Pet>> GetPetByIdAsync(
                long petId,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.Pet>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/pet/{petId}")
                  .WithOrAuth(orAuth => orAuth
                      .Add("api_key")
                      .Add("petstore_auth")
                  )
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("petId", petId))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Invalid ID supplied", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("Pet not found", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("0", CreateErrorCase("Unexpected error", (errorReason, context) => new ApiException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Updates a pet resource based on the form data.
        /// </summary>
        /// <param name="petId">Required parameter: ID of pet that needs to be updated.</param>
        /// <param name="name">Optional parameter: Name of pet that needs to be updated.</param>
        /// <param name="status">Optional parameter: Status of pet that needs to be updated.</param>
        /// <returns>Returns the ApiResponse of Models.Pet response from the API call.</returns>
        public ApiResponse<Models.Pet> UpdatePetWithForm(
                long petId,
                string name = null,
                string status = null)
            => CoreHelper.RunTask(UpdatePetWithFormAsync(petId, name, status));

        /// <summary>
        /// Updates a pet resource based on the form data.
        /// </summary>
        /// <param name="petId">Required parameter: ID of pet that needs to be updated.</param>
        /// <param name="name">Optional parameter: Name of pet that needs to be updated.</param>
        /// <param name="status">Optional parameter: Status of pet that needs to be updated.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.Pet response from the API call.</returns>
        public async Task<ApiResponse<Models.Pet>> UpdatePetWithFormAsync(
                long petId,
                string name = null,
                string status = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.Pet>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/pet/{petId}")
                  .WithAuth("petstore_auth")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("petId", petId))
                      .Query(query => query.Setup("name", name))
                      .Query(query => query.Setup("status", status))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Invalid input", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("0", CreateErrorCase("Unexpected error", (errorReason, context) => new ApiException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Delete a pet.
        /// </summary>
        /// <param name="petId">Required parameter: Pet id to delete.</param>
        /// <param name="apiKey">Optional parameter: .</param>
        public void DeletePet(
                long petId,
                string apiKey = null)
            => CoreHelper.RunVoidTask(DeletePetAsync(petId, apiKey));

        /// <summary>
        /// Delete a pet.
        /// </summary>
        /// <param name="petId">Required parameter: Pet id to delete.</param>
        /// <param name="apiKey">Optional parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the void response from the API call.</returns>
        public async Task DeletePetAsync(
                long petId,
                string apiKey = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<VoidType>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Delete, "/pet/{petId}")
                  .WithAuth("petstore_auth")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("petId", petId))
                      .Header(header => header.Setup("api_key", apiKey))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Invalid pet value", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("0", CreateErrorCase("Unexpected error", (errorReason, context) => new ApiException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Upload image of the pet.
        /// </summary>
        /// <param name="petId">Required parameter: ID of pet to update.</param>
        /// <param name="additionalMetadata">Optional parameter: Additional Metadata.</param>
        /// <param name="body">Optional parameter: .</param>
        /// <returns>Returns the ApiResponse of Models.ApiResponse response from the API call.</returns>
        public ApiResponse<Models.ApiResponse> UploadFile(
                long petId,
                string additionalMetadata = null,
                FileStreamInfo body = null)
            => CoreHelper.RunTask(UploadFileAsync(petId, additionalMetadata, body));

        /// <summary>
        /// Upload image of the pet.
        /// </summary>
        /// <param name="petId">Required parameter: ID of pet to update.</param>
        /// <param name="additionalMetadata">Optional parameter: Additional Metadata.</param>
        /// <param name="body">Optional parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.ApiResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.ApiResponse>> UploadFileAsync(
                long petId,
                string additionalMetadata = null,
                FileStreamInfo body = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.ApiResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/pet/{petId}/uploadImage")
                  .WithAuth("petstore_auth")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("petId", petId))
                      .Header(header => header.Setup("Content-Type", "application/octet-stream"))
                      .Query(query => query.Setup("additionalMetadata", additionalMetadata))
                      .Form(form => form.Setup("body", body))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("No file uploaded", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("Pet not found", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("0", CreateErrorCase("Unexpected error", (errorReason, context) => new ApiException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}