// <copyright file="StoreApi.cs" company="APIMatic">
// SwaggerPetstoreOpenApi30.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Types;
using APIMatic.Core.Utilities;
using SwaggerPetstoreOpenApi30.Standard.Exceptions;
using SwaggerPetstoreOpenApi30.Standard.Http.Response;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace SwaggerPetstoreOpenApi30.Standard.Apis
{
    /// <summary>
    /// StoreApi.
    /// </summary>
    public class StoreApi : BaseApi
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StoreApi"/> class.
        /// </summary>
        internal StoreApi(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// Returns a map of status codes to quantities.
        /// </summary>
        /// <returns>Returns the ApiResponse of Dictionary of string, int response from the API call.</returns>
        public ApiResponse<Dictionary<string, int>> GetInventory()
            => CoreHelper.RunTask(GetInventoryAsync());

        /// <summary>
        /// Returns a map of status codes to quantities.
        /// </summary>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Dictionary of string, int response from the API call.</returns>
        public async Task<ApiResponse<Dictionary<string, int>>> GetInventoryAsync(CancellationToken cancellationToken = default)
            => await CreateApiCall<Dictionary<string, int>>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/store/inventory")
                  .WithAuth("api_key"))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Unexpected error", (errorReason, context) => new ApiException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Place a new order in the store.
        /// </summary>
        /// <param name="id">Optional parameter: .</param>
        /// <param name="petId">Optional parameter: .</param>
        /// <param name="quantity">Optional parameter: .</param>
        /// <param name="shipDate">Optional parameter: .</param>
        /// <param name="status">Optional parameter: Order Status.</param>
        /// <param name="complete">Optional parameter: .</param>
        /// <returns>Returns the ApiResponse of Models.Order response from the API call.</returns>
        public ApiResponse<Models.Order> PlaceOrder(
                long? id = null,
                long? petId = null,
                int? quantity = null,
                DateTime? shipDate = null,
                Models.OrderStatus? status = null,
                bool? complete = null)
            => CoreHelper.RunTask(PlaceOrderAsync(id, petId, quantity, shipDate, status, complete));

        /// <summary>
        /// Place a new order in the store.
        /// </summary>
        /// <param name="id">Optional parameter: .</param>
        /// <param name="petId">Optional parameter: .</param>
        /// <param name="quantity">Optional parameter: .</param>
        /// <param name="shipDate">Optional parameter: .</param>
        /// <param name="status">Optional parameter: Order Status.</param>
        /// <param name="complete">Optional parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.Order response from the API call.</returns>
        public async Task<ApiResponse<Models.Order>> PlaceOrderAsync(
                long? id = null,
                long? petId = null,
                int? quantity = null,
                DateTime? shipDate = null,
                Models.OrderStatus? status = null,
                bool? complete = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.Order>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/store/order")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))
                      .Form(form => form.Setup("id", id))
                      .Form(form => form.Setup("petId", petId))
                      .Form(form => form.Setup("quantity", quantity))
                      .Form(form => form.Setup("shipDate", shipDate.HasValue ? shipDate.Value.ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK") : null))
                      .Form(form => form.Setup("status", (status.HasValue) ? CoreHelper.JsonSerialize(status.Value).Trim('\"') : null))
                      .Form(form => form.Setup("complete", complete))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Invalid input", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("422", CreateErrorCase("Validation exception", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("0", CreateErrorCase("Unexpected error", (errorReason, context) => new ApiException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// <![CDATA[
        /// For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
        /// ]]>
        /// </summary>
        /// <param name="orderId">Required parameter: ID of order that needs to be fetched.</param>
        /// <returns>Returns the ApiResponse of Models.Order response from the API call.</returns>
        public ApiResponse<Models.Order> GetOrderById(
                long orderId)
            => CoreHelper.RunTask(GetOrderByIdAsync(orderId));

        /// <summary>
        /// <![CDATA[
        /// For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
        /// ]]>
        /// </summary>
        /// <param name="orderId">Required parameter: ID of order that needs to be fetched.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.Order response from the API call.</returns>
        public async Task<ApiResponse<Models.Order>> GetOrderByIdAsync(
                long orderId,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.Order>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/store/order/{orderId}")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("orderId", orderId))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Invalid ID supplied", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("Order not found", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("0", CreateErrorCase("Unexpected error", (errorReason, context) => new ApiException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// <![CDATA[
        /// For valid response try integer IDs with value < 1000. Anything above 1000 or non-integers will generate API errors.
        /// ]]>
        /// </summary>
        /// <param name="orderId">Required parameter: ID of the order that needs to be deleted.</param>
        public void DeleteOrder(
                long orderId)
            => CoreHelper.RunVoidTask(DeleteOrderAsync(orderId));

        /// <summary>
        /// <![CDATA[
        /// For valid response try integer IDs with value < 1000. Anything above 1000 or non-integers will generate API errors.
        /// ]]>
        /// </summary>
        /// <param name="orderId">Required parameter: ID of the order that needs to be deleted.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the void response from the API call.</returns>
        public async Task DeleteOrderAsync(
                long orderId,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<VoidType>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Delete, "/store/order/{orderId}")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("orderId", orderId))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Invalid ID supplied", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("Order not found", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("0", CreateErrorCase("Unexpected error", (errorReason, context) => new ApiException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}