// <copyright file="UserApi.cs" company="APIMatic">
// SwaggerPetstoreOpenApi30.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Types;
using APIMatic.Core.Utilities;
using SwaggerPetstoreOpenApi30.Standard.Exceptions;
using SwaggerPetstoreOpenApi30.Standard.Http.Response;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace SwaggerPetstoreOpenApi30.Standard.Apis
{
    /// <summary>
    /// UserApi.
    /// </summary>
    public class UserApi : BaseApi
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserApi"/> class.
        /// </summary>
        internal UserApi(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// This can only be done by the logged in user.
        /// </summary>
        /// <param name="id">Optional parameter: .</param>
        /// <param name="username">Optional parameter: .</param>
        /// <param name="firstName">Optional parameter: .</param>
        /// <param name="lastName">Optional parameter: .</param>
        /// <param name="email">Optional parameter: .</param>
        /// <param name="password">Optional parameter: .</param>
        /// <param name="phone">Optional parameter: .</param>
        /// <param name="userStatus">Optional parameter: User Status.</param>
        /// <returns>Returns the ApiResponse of Models.User response from the API call.</returns>
        public ApiResponse<Models.User> CreateUser(
                long? id = null,
                string username = null,
                string firstName = null,
                string lastName = null,
                string email = null,
                string password = null,
                string phone = null,
                int? userStatus = null)
            => CoreHelper.RunTask(CreateUserAsync(id, username, firstName, lastName, email, password, phone, userStatus));

        /// <summary>
        /// This can only be done by the logged in user.
        /// </summary>
        /// <param name="id">Optional parameter: .</param>
        /// <param name="username">Optional parameter: .</param>
        /// <param name="firstName">Optional parameter: .</param>
        /// <param name="lastName">Optional parameter: .</param>
        /// <param name="email">Optional parameter: .</param>
        /// <param name="password">Optional parameter: .</param>
        /// <param name="phone">Optional parameter: .</param>
        /// <param name="userStatus">Optional parameter: User Status.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.User response from the API call.</returns>
        public async Task<ApiResponse<Models.User>> CreateUserAsync(
                long? id = null,
                string username = null,
                string firstName = null,
                string lastName = null,
                string email = null,
                string password = null,
                string phone = null,
                int? userStatus = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.User>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/user")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))
                      .Form(form => form.Setup("id", id))
                      .Form(form => form.Setup("username", username))
                      .Form(form => form.Setup("firstName", firstName))
                      .Form(form => form.Setup("lastName", lastName))
                      .Form(form => form.Setup("email", email))
                      .Form(form => form.Setup("password", password))
                      .Form(form => form.Setup("phone", phone))
                      .Form(form => form.Setup("userStatus", userStatus))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Unexpected error", (errorReason, context) => new ApiException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Creates list of users with given input array.
        /// </summary>
        /// <param name="body">Optional parameter: .</param>
        /// <returns>Returns the ApiResponse of Models.User response from the API call.</returns>
        public ApiResponse<Models.User> CreateUsersWithListInput(
                List<Models.User> body = null)
            => CoreHelper.RunTask(CreateUsersWithListInputAsync(body));

        /// <summary>
        /// Creates list of users with given input array.
        /// </summary>
        /// <param name="body">Optional parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.User response from the API call.</returns>
        public async Task<ApiResponse<Models.User>> CreateUsersWithListInputAsync(
                List<Models.User> body = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.User>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/user/createWithList")
                  .Parameters(parameters => parameters
                      .Body(b => b.Setup(body))
                      .Header(header => header.Setup("Content-Type", "application/json"))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Unexpected error", (errorReason, context) => new ApiException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Log into the system.
        /// </summary>
        /// <param name="username">Optional parameter: The user name for login.</param>
        /// <param name="password">Optional parameter: The password for login in clear text.</param>
        /// <returns>Returns the ApiResponse of string response from the API call.</returns>
        public ApiResponse<string> LoginUser(
                string username = null,
                string password = null)
            => CoreHelper.RunTask(LoginUserAsync(username, password));

        /// <summary>
        /// Log into the system.
        /// </summary>
        /// <param name="username">Optional parameter: The user name for login.</param>
        /// <param name="password">Optional parameter: The password for login in clear text.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of string response from the API call.</returns>
        public async Task<ApiResponse<string>> LoginUserAsync(
                string username = null,
                string password = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<string>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/user/login")
                  .Parameters(parameters => parameters
                      .Query(query => query.Setup("username", username))
                      .Query(query => query.Setup("password", password))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Invalid username/password supplied", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("0", CreateErrorCase("Unexpected error", (errorReason, context) => new ApiException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Log user out of the system.
        /// </summary>
        public void LogoutUser()
            => CoreHelper.RunVoidTask(LogoutUserAsync());

        /// <summary>
        /// Log user out of the system.
        /// </summary>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the void response from the API call.</returns>
        public async Task LogoutUserAsync(CancellationToken cancellationToken = default)
            => await CreateApiCall<VoidType>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/user/logout"))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Unexpected error", (errorReason, context) => new ApiException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Get user detail based on username.
        /// </summary>
        /// <param name="usersname">Required parameter: The username that needs to be processed.</param>
        /// <returns>Returns the ApiResponse of Models.User response from the API call.</returns>
        public ApiResponse<Models.User> GetUserByName(
                string usersname)
            => CoreHelper.RunTask(GetUserByNameAsync(usersname));

        /// <summary>
        /// Get user detail based on username.
        /// </summary>
        /// <param name="usersname">Required parameter: The username that needs to be processed.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.User response from the API call.</returns>
        public async Task<ApiResponse<Models.User>> GetUserByNameAsync(
                string usersname,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.User>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/user/{usersname}")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("usersname", usersname).Required())))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Invalid username supplied", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("User not found", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("0", CreateErrorCase("Unexpected error", (errorReason, context) => new ApiException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// This can only be done by the logged in user.
        /// </summary>
        /// <param name="usersname">Required parameter: The username that needs to be processed.</param>
        /// <param name="id">Optional parameter: .</param>
        /// <param name="username">Optional parameter: .</param>
        /// <param name="firstName">Optional parameter: .</param>
        /// <param name="lastName">Optional parameter: .</param>
        /// <param name="email">Optional parameter: .</param>
        /// <param name="password">Optional parameter: .</param>
        /// <param name="phone">Optional parameter: .</param>
        /// <param name="userStatus">Optional parameter: User Status.</param>
        public void UpdateUser(
                string usersname,
                long? id = null,
                string username = null,
                string firstName = null,
                string lastName = null,
                string email = null,
                string password = null,
                string phone = null,
                int? userStatus = null)
            => CoreHelper.RunVoidTask(UpdateUserAsync(usersname, id, username, firstName, lastName, email, password, phone, userStatus));

        /// <summary>
        /// This can only be done by the logged in user.
        /// </summary>
        /// <param name="usersname">Required parameter: The username that needs to be processed.</param>
        /// <param name="id">Optional parameter: .</param>
        /// <param name="username">Optional parameter: .</param>
        /// <param name="firstName">Optional parameter: .</param>
        /// <param name="lastName">Optional parameter: .</param>
        /// <param name="email">Optional parameter: .</param>
        /// <param name="password">Optional parameter: .</param>
        /// <param name="phone">Optional parameter: .</param>
        /// <param name="userStatus">Optional parameter: User Status.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the void response from the API call.</returns>
        public async Task UpdateUserAsync(
                string usersname,
                long? id = null,
                string username = null,
                string firstName = null,
                string lastName = null,
                string email = null,
                string password = null,
                string phone = null,
                int? userStatus = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<VoidType>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Put, "/user/{usersname}")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("usersname", usersname).Required())
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))
                      .Form(form => form.Setup("id", id))
                      .Form(form => form.Setup("username", username))
                      .Form(form => form.Setup("firstName", firstName))
                      .Form(form => form.Setup("lastName", lastName))
                      .Form(form => form.Setup("email", email))
                      .Form(form => form.Setup("password", password))
                      .Form(form => form.Setup("phone", phone))
                      .Form(form => form.Setup("userStatus", userStatus))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("bad request", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("user not found", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("0", CreateErrorCase("Unexpected error", (errorReason, context) => new ApiException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// This can only be done by the logged in user.
        /// </summary>
        /// <param name="usersname">Required parameter: The username that needs to be processed.</param>
        public void DeleteUser(
                string usersname)
            => CoreHelper.RunVoidTask(DeleteUserAsync(usersname));

        /// <summary>
        /// This can only be done by the logged in user.
        /// </summary>
        /// <param name="usersname">Required parameter: The username that needs to be processed.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the void response from the API call.</returns>
        public async Task DeleteUserAsync(
                string usersname,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<VoidType>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Delete, "/user/{usersname}")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("usersname", usersname).Required())))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Invalid username supplied", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("User not found", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("0", CreateErrorCase("Unexpected error", (errorReason, context) => new ApiException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}